### ISSUE TITLE
compilation issue

### ISSUE THREAD

**Issue by dineshkumarreddyg36** [STREAmS-CFD/STREAmS-2#3]
Hello,
I was trying to compile the code with intel compiler and I got the following error:
![intel_error](https://user-images.githubusercontent.com/106377425/231377734-6d39be23-4793-44e2-b766-782d5d89f599.PNG)

to avoid this error I commented line 15 - 18 in Makefile
![makefile](https://user-images.githubusercontent.com/106377425/231378086-45fed439-d181-417b-9e7d-471ef845629b.PNG)

After this I got this error
![intel2](https://user-images.githubusercontent.com/106377425/231378282-68a95558-1b48-4e94-8638-468303139369.PNG)
Can  you please suggest what is to be done.

Thank you

**Comment by francescosalvadore** [comment]
Hello,

There was a bug in the order of function arguments that was (correctly) detected by the Intel compiler. It should be fixed in the last commit.

C code is always compiled with the GNU compiler so you also need a modern gcc/g++ that supports -std=c++17.

If you also want to compile C code using the Intel compiler, you can comment out the 4 lines as you did and then you have to add -lstdc++ to the linking. For example you can add the variable FCLIBS = -lstdc++ to the bottom of the makefile.inc you are using.

Francesco
